{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "krate.fullname" . }}-default
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector: {}
  egress:
    - to:
        - namespaceSelector: {}
{{- if .Values.jitsi.install }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "krate.fullname" . }}-jitsi-media
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/instance
        operator: In
        values:
          - {{ .Release.Name }}
      - key: app.kubernetes.io/component
        operator: In
        values:
          - jvb
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: UDP
          port: {{ .Values.jitsi.jvb.service.udpPort | default 10000 }}
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 5222
        - protocol: TCP
          port: {{ .Values.jitsi.prosody.http.port | default 5280 }}
        - protocol: UDP
          port: {{ .Values.jitsi.jvb.service.udpPort | default 10000 }}
{{- end }}
{{- end -}}
