import { test, expect } from "../fixtures";
import { getManifest, type Manifest } from "../fixtures/test-data";

/**
 * Comprehensive E2E tests for the Observer Dashboard page (/).
 *
 * These tests run against fixture data generated by generate-fixtures.ts.
 * The fixture manifest provides deterministic counts for assertions.
 */

let manifest: Manifest;

test.beforeAll(async () => {
  manifest = await getManifest();
});

// ---------------------------------------------------------------------------
// Dashboard Loading & Header
// ---------------------------------------------------------------------------

test.describe("Dashboard Loading", () => {
  test("loads the dashboard and displays the header", async ({ dashboardPage }) => {
    await dashboardPage.goto();
    await expect(dashboardPage.heading).toBeVisible({ timeout: 30_000 });
    await expect(dashboardPage.header).toBeVisible();
  });

  test("displays the SSE connection status indicator", async ({ dashboardPage }) => {
    await dashboardPage.goto();
    await expect(dashboardPage.heading).toBeVisible({ timeout: 30_000 });
    await expect(dashboardPage.connectionDot).toBeVisible();
  });

  test("shows settings button in the top bar", async ({ dashboardPage }) => {
    await dashboardPage.goto();
    await expect(dashboardPage.heading).toBeVisible({ timeout: 30_000 });
    await expect(dashboardPage.settingsButton).toBeVisible();
  });

  test("loading skeletons disappear once data loads", async ({ dashboardPage }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();

    // Skeletons should no longer be visible
    const skeletons = dashboardPage.loadingSkeletons;
    // The main content skeletons (3 placeholders) should be gone
    await expect(dashboardPage.projectGrid).toBeVisible({ timeout: 30_000 });
  });
});

// ---------------------------------------------------------------------------
// KPI Metric Tiles
// ---------------------------------------------------------------------------

test.describe("KPI Metric Tiles", () => {
  test.beforeEach(async ({ dashboardPage }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();
  });

  test("displays KPI metric tiles (4 base, or 5 with Stale)", async ({ dashboardPage }) => {
    await expect(dashboardPage.kpiGrid).toBeVisible();
    const tiles = dashboardPage.getKPITiles();
    const count = await tiles.count();
    // 4 base tiles (Total Runs, Active, Completed, Failed) + optional Stale tile
    expect(count).toBeGreaterThanOrEqual(4);
    expect(count).toBeLessThanOrEqual(5);
  });

  test("Total Runs tile shows the correct count", async ({ dashboardPage }) => {
    const tile = dashboardPage.getMetricTile("total-runs");
    await expect(tile).toBeVisible();
    await expect(tile).toContainText("Total Runs");
    await expect(tile).toContainText(String(manifest.runCount));
  });

  test("Active tile shows the active run count", async ({ dashboardPage }) => {
    const tile = dashboardPage.getMetricTile("active");
    await expect(tile).toBeVisible();
    await expect(tile).toContainText("In Progress");
    // Active = waiting + pending
    const activeCount =
      (manifest.statusCounts.waiting || 0) + (manifest.statusCounts.pending || 0);
    await expect(tile).toContainText(String(activeCount));
  });

  test("Completed tile shows the completed run count", async ({ dashboardPage }) => {
    const tile = dashboardPage.getMetricTile("completed");
    await expect(tile).toBeVisible();
    await expect(tile).toContainText("Completed");
    await expect(tile).toContainText(String(manifest.statusCounts.completed || 0));
  });

  test("Failed tile shows the failed run count", async ({ dashboardPage }) => {
    const tile = dashboardPage.getMetricTile("failed");
    await expect(tile).toBeVisible();
    await expect(tile).toContainText("Failed");
    await expect(tile).toContainText(String(manifest.statusCounts.failed || 0));
  });

  test("KPI tile values sum correctly", async ({ dashboardPage }) => {
    // The active + completed + failed should generally equal total
    // (pending are included in active)
    const totalTile = dashboardPage.getMetricTile("total-runs");
    const totalText = await totalTile.innerText();
    const totalValue = parseInt(totalText.match(/\d+/)?.[0] || "0", 10);
    expect(totalValue).toBe(manifest.runCount);
  });
});

// ---------------------------------------------------------------------------
// Project Health Cards
// ---------------------------------------------------------------------------

test.describe("Project Health Cards", () => {
  test.beforeEach(async ({ dashboardPage }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();
  });

  test("renders all project cards from fixtures", async ({ dashboardPage }) => {
    const projectNames = Object.keys(manifest.projectCounts);
    const cards = dashboardPage.getProjectCards();
    await expect(cards).toHaveCount(projectNames.length);
  });

  test("project count label shows the correct number", async ({ dashboardPage }) => {
    const projectNames = Object.keys(manifest.projectCounts);
    await expect(dashboardPage.projectCount).toContainText(
      `${projectNames.length} project`
    );
  });

  test("each project card displays the project name", async ({ dashboardPage }) => {
    const projectNames = Object.keys(manifest.projectCounts);
    for (const name of projectNames) {
      const card = dashboardPage.getProjectCard(name);
      await expect(card).toBeVisible();
      await expect(card).toContainText(name);
    }
  });

  test("project cards show health status label", async ({ dashboardPage }) => {
    // Every project card should show one of: Healthy, Active, Failing
    const cards = dashboardPage.getProjectCards();
    const count = await cards.count();
    for (let i = 0; i < count; i++) {
      const card = cards.nth(i);
      const text = await card.innerText();
      const hasHealthLabel =
        text.includes("Healthy") ||
        text.includes("Active") ||
        text.includes("Failing");
      expect(hasHealthLabel).toBe(true);
    }
  });

  test("project cards display total run count", async ({ dashboardPage }) => {
    // Each project card should contain a number representing total runs.
    // Use Playwright's auto-retrying toContainText instead of a one-shot
    // innerText() read, which can flake when cards are still hydrating.
    const cards = dashboardPage.getProjectCards();
    const count = await cards.count();
    expect(count).toBeGreaterThan(0);

    for (let i = 0; i < count; i++) {
      await expect(cards.nth(i)).toContainText(/\d+/, { timeout: 10_000 });
    }
  });

  test("project cards show progress bar when tasks exist", async ({ dashboardPage }) => {
    // At least one project card should have a progress bar (tasks text)
    const cards = dashboardPage.getProjectCards();
    const count = await cards.count();
    let foundProgress = false;
    for (let i = 0; i < count; i++) {
      const text = await cards.nth(i).innerText();
      if (text.includes("tasks")) {
        foundProgress = true;
        break;
      }
    }
    expect(foundProgress).toBe(true);
  });

  test("expanding a project card reveals run cards", async ({ dashboardPage, page }) => {
    // Click the first project card to expand it
    const firstCard = dashboardPage.getProjectCards().first();
    await firstCard.click();

    // Expand collapsed sub-sections (Failed Runs, Completed History) if present
    await dashboardPage.expandRunSubSections();

    // Wait for run cards to appear inside the expanded card
    const runCards = dashboardPage.getRunCards();
    await expect(runCards.first()).toBeVisible({ timeout: 15_000 });
  });
});

// ---------------------------------------------------------------------------
// Filter Pills
// ---------------------------------------------------------------------------

test.describe("Filter Pills", () => {
  test.beforeEach(async ({ dashboardPage }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();
  });

  test("displays all filter pills (4 base, or 5 with Stale)", async ({ dashboardPage }) => {
    const pills = dashboardPage.getFilterPills();
    const count = await pills.count();
    // 4 base pills (All, Running, Completed, Failed) + optional Stale pill
    expect(count).toBeGreaterThanOrEqual(4);
    expect(count).toBeLessThanOrEqual(5);
  });

  test("All filter pill is active by default", async ({ dashboardPage }) => {
    const allPill = dashboardPage.getFilterPill("all");
    await expect(allPill).toBeVisible();
    // The active pill has bg-primary/10 class (visually highlighted)
    await expect(allPill).toHaveClass(/bg-primary/);
  });

  test("filter pills display correct labels", async ({ dashboardPage }) => {
    await expect(dashboardPage.getFilterPill("all")).toContainText("All");
    await expect(dashboardPage.getFilterPill("waiting")).toContainText("Running");
    await expect(dashboardPage.getFilterPill("completed")).toContainText("Completed");
    await expect(dashboardPage.getFilterPill("failed")).toContainText("Failed");
  });

  test("filter pills show count badges when runs exist", async ({ dashboardPage }) => {
    // The "All" pill should show the total run count
    const allPill = dashboardPage.getFilterPill("all");
    await expect(allPill).toContainText(String(manifest.runCount));

    // Completed pill should show completed count
    if ((manifest.statusCounts.completed || 0) > 0) {
      const completedPill = dashboardPage.getFilterPill("completed");
      await expect(completedPill).toContainText(
        String(manifest.statusCounts.completed)
      );
    }

    // Failed pill should show failed count
    if ((manifest.statusCounts.failed || 0) > 0) {
      const failedPill = dashboardPage.getFilterPill("failed");
      await expect(failedPill).toContainText(String(manifest.statusCounts.failed));
    }
  });

  test("clicking Running filter shows only projects with active runs", async ({
    dashboardPage,
  }) => {
    await dashboardPage.clickFilter("Running");

    // The active pill should change to Running
    const runningPill = dashboardPage.getFilterPill("waiting");
    await expect(runningPill).toHaveClass(/bg-primary/);

    // Projects displayed should only be those with active runs
    // Count projects that have waiting or pending runs
    const activeProjectNames = new Set(
      manifest.runs
        .filter((r) => r.status === "waiting" || r.status === "pending")
        .map((r) => r.projectName)
    );

    const cards = dashboardPage.getProjectCards();
    const cardCount = await cards.count();
    expect(cardCount).toBe(activeProjectNames.size);

    // Project count label should update
    await expect(dashboardPage.projectCount).toContainText(
      `${activeProjectNames.size} project`
    );
  });

  test("clicking Completed filter shows only projects with completed runs", async ({
    dashboardPage,
  }) => {
    await dashboardPage.clickFilter("Completed");

    const completedPill = dashboardPage.getFilterPill("completed");
    await expect(completedPill).toHaveClass(/bg-primary/);

    // Count projects that have completed runs
    const completedProjectNames = new Set(
      manifest.runs
        .filter((r) => r.status === "completed")
        .map((r) => r.projectName)
    );

    const cards = dashboardPage.getProjectCards();
    const cardCount = await cards.count();
    expect(cardCount).toBe(completedProjectNames.size);
  });

  test("clicking Failed filter shows only projects with failed runs", async ({
    dashboardPage,
  }) => {
    await dashboardPage.clickFilter("Failed");

    const failedPill = dashboardPage.getFilterPill("failed");
    await expect(failedPill).toHaveClass(/bg-primary/);

    // Count projects that have failed runs
    const failedProjectNames = new Set(
      manifest.runs
        .filter((r) => r.status === "failed")
        .map((r) => r.projectName)
    );

    const cards = dashboardPage.getProjectCards();
    const cardCount = await cards.count();
    expect(cardCount).toBe(failedProjectNames.size);
  });

  test("clicking All filter restores all projects", async ({ dashboardPage }) => {
    // First apply a filter
    await dashboardPage.clickFilter("Failed");
    const failedProjectNames = new Set(
      manifest.runs
        .filter((r) => r.status === "failed")
        .map((r) => r.projectName)
    );
    const cards = dashboardPage.getProjectCards();
    await expect(cards).toHaveCount(failedProjectNames.size);

    // Now click All to restore
    await dashboardPage.clickFilter("All");

    const allPill = dashboardPage.getFilterPill("all");
    await expect(allPill).toHaveClass(/bg-primary/);

    const allProjects = Object.keys(manifest.projectCounts);
    await expect(dashboardPage.getProjectCards()).toHaveCount(allProjects.length);
  });

  test("switching filters updates the project count label", async ({
    dashboardPage,
  }) => {
    const totalProjects = Object.keys(manifest.projectCounts).length;

    // Initially shows all projects
    await expect(dashboardPage.projectCount).toContainText(
      `${totalProjects} project`
    );

    // Switch to Failed
    await dashboardPage.clickFilter("Failed");
    const failedProjectCount = new Set(
      manifest.runs
        .filter((r) => r.status === "failed")
        .map((r) => r.projectName)
    ).size;
    await expect(dashboardPage.projectCount).toContainText(
      `${failedProjectCount} project`
    );

    // Switch back to All
    await dashboardPage.clickFilter("All");
    await expect(dashboardPage.projectCount).toContainText(
      `${totalProjects} project`
    );
  });
});

// ---------------------------------------------------------------------------
// Run Cards & Navigation
// ---------------------------------------------------------------------------

test.describe("Run Cards", () => {
  test.beforeEach(async ({ dashboardPage }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();
  });

  test("expanding a project card shows run cards with status badges", async ({
    dashboardPage,
    page,
  }) => {
    // Expand the first project card
    const firstCard = dashboardPage.getProjectCards().first();
    await firstCard.click();

    // Expand collapsed sub-sections (Failed Runs, Completed History) if present
    await dashboardPage.expandRunSubSections();

    // Wait for run cards to load
    const runCards = dashboardPage.getRunCards();
    await expect(runCards.first()).toBeVisible({ timeout: 15_000 });

    // Each run card should contain a status badge text
    const count = await runCards.count();
    expect(count).toBeGreaterThan(0);

    for (let i = 0; i < Math.min(count, 5); i++) {
      const cardText = await runCards.nth(i).innerText();
      const hasStatus =
        cardText.includes("Completed") ||
        cardText.includes("Waiting") ||
        cardText.includes("Working") ||
        cardText.includes("Failed") ||
        cardText.includes("Running") ||
        cardText.includes("Pending");
      expect(hasStatus).toBe(true);
    }
  });

  test("run cards display task progress", async ({ dashboardPage }) => {
    // Expand the first project card
    const firstCard = dashboardPage.getProjectCards().first();
    await firstCard.click();

    // Expand collapsed sub-sections (Failed Runs, Completed History) if present
    await dashboardPage.expandRunSubSections();

    const runCards = dashboardPage.getRunCards();
    await expect(runCards.first()).toBeVisible({ timeout: 15_000 });

    // Run cards should show task counts like "X/Y tasks"
    const firstRunText = await runCards.first().innerText();
    expect(firstRunText).toMatch(/\d+\/\d+ tasks/);
  });

  test("run cards display duration", async ({ dashboardPage }) => {
    // Expand the first project card
    const firstCard = dashboardPage.getProjectCards().first();
    await firstCard.click();

    // Expand collapsed sub-sections (Failed Runs, Completed History) if present
    await dashboardPage.expandRunSubSections();

    const runCards = dashboardPage.getRunCards();
    await expect(runCards.first()).toBeVisible({ timeout: 15_000 });

    // Run cards should show duration (e.g. "2m 30s" or "< 1s")
    const firstRunText = await runCards.first().innerText();
    // Duration format: Xs, Xm, Xh, or "< 1s"
    expect(firstRunText).toMatch(/(\d+[smh]|< 1s)/);
  });

  test("clicking a run card navigates to /runs/[runId]", async ({
    dashboardPage,
    page,
  }) => {
    // Expand the first project card
    const firstCard = dashboardPage.getProjectCards().first();
    await firstCard.click();

    // Expand collapsed sub-sections (Failed Runs, Completed History) if present
    await dashboardPage.expandRunSubSections();

    // Wait for run cards
    const runCards = dashboardPage.getRunCards();
    await expect(runCards.first()).toBeVisible({ timeout: 15_000 });

    // Get the href of the first run card
    const href = await runCards.first().getAttribute("href");
    expect(href).toMatch(/^\/runs\/[A-Z0-9]+$/);

    // Click the first run card
    await runCards.first().click();

    // Verify navigation to the run detail page
    await page.waitForURL(/\/runs\/[A-Z0-9]+/, { timeout: 30_000 });
    expect(page.url()).toContain("/runs/");
  });

  test("run card links have valid runId in href", async ({ dashboardPage }) => {
    // Expand the first project card
    const firstCard = dashboardPage.getProjectCards().first();
    await firstCard.click();

    // Expand collapsed sub-sections (Failed Runs, Completed History) if present
    await dashboardPage.expandRunSubSections();

    const runCards = dashboardPage.getRunCards();
    await expect(runCards.first()).toBeVisible({ timeout: 15_000 });

    const count = await runCards.count();
    for (let i = 0; i < Math.min(count, 5); i++) {
      const href = await runCards.nth(i).getAttribute("href");
      expect(href).toBeTruthy();
      expect(href).toMatch(/^\/runs\/01[A-Z0-9]+$/);
    }
  });
});

// ---------------------------------------------------------------------------
// Pagination within Expanded Project Cards
// ---------------------------------------------------------------------------

test.describe("Pagination", () => {
  test("pagination controls appear for projects with more than 5 runs", async ({
    dashboardPage,
    page,
  }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();

    // Find a project with more than 5 runs
    const projectsWithManyRuns = Object.entries(manifest.projectCounts)
      .filter(([_, count]) => count > 5)
      .map(([name]) => name);

    if (projectsWithManyRuns.length === 0) {
      test.skip();
      return;
    }

    const projectName = projectsWithManyRuns[0];
    const card = dashboardPage.getProjectCard(projectName);
    await card.click();

    // Expand collapsed sub-sections (Failed Runs, Completed History) if present
    await dashboardPage.expandRunSubSections();

    // Wait for run cards to load
    const runCards = page.locator(
      `[data-testid="project-card-${projectName}"] a[href^="/runs/"]`
    );
    await expect(runCards.first()).toBeVisible({ timeout: 15_000 });

    // Pagination controls should be visible (Previous/Next page buttons)
    const prevButton = page.getByRole("button", { name: "Previous page" });
    const nextButton = page.getByRole("button", { name: "Next page" });

    await expect(nextButton).toBeVisible({ timeout: 5_000 });

    // Previous button should be disabled on first page
    await expect(prevButton).toBeDisabled();
  });

  test("clicking next page loads more runs", async ({ dashboardPage, page }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();

    // Find a project with more than 5 runs
    const projectsWithManyRuns = Object.entries(manifest.projectCounts)
      .filter(([_, count]) => count > 5)
      .map(([name]) => name);

    if (projectsWithManyRuns.length === 0) {
      test.skip();
      return;
    }

    const projectName = projectsWithManyRuns[0];
    const card = dashboardPage.getProjectCard(projectName);
    await card.click();

    // Expand collapsed sub-sections (Failed Runs, Completed History) if present
    await dashboardPage.expandRunSubSections();

    // Wait for runs to load
    const projectCard = page.getByTestId(`project-card-${projectName}`);
    const runCards = projectCard.locator('a[href^="/runs/"]');
    await expect(runCards.first()).toBeVisible({ timeout: 15_000 });

    // Should show up to 5 runs on first page
    const firstPageCount = await runCards.count();
    expect(firstPageCount).toBeLessThanOrEqual(5);

    // Click next page
    const nextButton = projectCard.getByRole("button", { name: "Next page" });
    await nextButton.click();

    // Wait for new runs to appear (the content will update)
    await page.waitForTimeout(1000);

    // The page indicator should now show "2"
    const pageIndicator = projectCard.locator(
      ".text-primary.bg-primary\\/10"
    );
    await expect(pageIndicator).toContainText("2");
  });
});

// ---------------------------------------------------------------------------
// Empty State (when filter yields no matching projects)
// ---------------------------------------------------------------------------

test.describe("Empty State", () => {
  test("shows empty state text when no projects match a filter that has zero count", async ({
    dashboardPage,
    page,
  }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();

    // Apply filters and verify the project count updates.
    // If all projects have at least one run of each type, we may not see an empty state.
    // We can verify the empty-state fallback logic by checking the filter behavior.

    // Check if any filter would result in 0 projects
    const failedProjects = new Set(
      manifest.runs
        .filter((r) => r.status === "failed")
        .map((r) => r.projectName)
    );
    const completedProjects = new Set(
      manifest.runs
        .filter((r) => r.status === "completed")
        .map((r) => r.projectName)
    );
    const activeProjects = new Set(
      manifest.runs
        .filter((r) => r.status === "waiting" || r.status === "pending")
        .map((r) => r.projectName)
    );

    // If all 4 projects appear in every filter, there's no empty state to test
    // In that case, just verify the empty state element exists in the DOM markup
    // by expanding a project card and filtering to a status with no matching runs
    const allProjectCount = Object.keys(manifest.projectCounts).length;
    if (
      failedProjects.size < allProjectCount ||
      completedProjects.size < allProjectCount ||
      activeProjects.size < allProjectCount
    ) {
      // Find a filter that produces fewer projects
      if (failedProjects.size < allProjectCount) {
        await dashboardPage.clickFilter("Failed");
        const cards = dashboardPage.getProjectCards();
        const count = await cards.count();
        expect(count).toBeLessThan(allProjectCount);
      }
    }
  });

  test("empty state shows configure message when no runs match within a project", async ({
    dashboardPage,
    page,
  }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();

    // Apply the Failed filter
    await dashboardPage.clickFilter("Failed");

    // Find a project with failed runs
    const failedProjectNames = [
      ...new Set(
        manifest.runs
          .filter((r) => r.status === "failed")
          .map((r) => r.projectName)
      ),
    ];

    if (failedProjectNames.length === 0) {
      test.skip();
      return;
    }

    // Now expand a project that has failed runs - runs should display
    const projectName = failedProjectNames[0];
    const card = dashboardPage.getProjectCard(projectName);
    await card.click();

    // Expand collapsed sub-sections (Failed Runs, Completed History) if present
    await dashboardPage.expandRunSubSections();

    // Wait for run list to appear
    const runCards = card.locator('a[href^="/runs/"]');
    await expect(runCards.first()).toBeVisible({ timeout: 15_000 });

    // Now switch to Completed filter while the card is expanded
    await dashboardPage.clickFilter("Completed");

    // The card may disappear if the project has no completed runs
    const hasCompletedRuns = manifest.runs.some(
      (r) => r.projectName === projectName && r.status === "completed"
    );

    if (!hasCompletedRuns) {
      // The card should no longer be visible (project filtered out)
      await expect(card).not.toBeVisible({ timeout: 5_000 });
    }
  });
});

// ---------------------------------------------------------------------------
// Theme Toggle
// ---------------------------------------------------------------------------

test.describe("Theme Toggle", () => {
  test("theme toggle button is accessible", async ({ dashboardPage, page }) => {
    await dashboardPage.goto();
    await expect(dashboardPage.heading).toBeVisible({ timeout: 30_000 });

    // The theme toggle button should have a title attribute
    const themeButton = page.locator("button[title*='Switch to']");
    await expect(themeButton).toBeVisible();

    const title = await themeButton.getAttribute("title");
    expect(title).toMatch(/Switch to (light|dark) theme/);
  });
});

// ---------------------------------------------------------------------------
// Settings Modal
// ---------------------------------------------------------------------------

test.describe("Settings Modal", () => {
  test("clicking settings button opens settings modal", async ({
    dashboardPage,
    page,
  }) => {
    await dashboardPage.goto();
    await expect(dashboardPage.heading).toBeVisible({ timeout: 30_000 });

    // Wait for the page to fully stabilize before clicking the settings button.
    // The dashboard may still be loading data which can cause SSE-related re-renders
    // that interfere with the click handler registration.
    await dashboardPage.waitForData();

    await dashboardPage.settingsButton.click();

    // Settings modal should become visible (Radix Dialog.Portal may take a moment)
    await expect(page.getByTestId("settings-modal")).toBeVisible({ timeout: 30_000 });
  });
});

// ---------------------------------------------------------------------------
// Cross-Cutting Concerns
// ---------------------------------------------------------------------------

test.describe("Dashboard Accessibility", () => {
  test("page has a main heading", async ({ dashboardPage }) => {
    await dashboardPage.goto();
    const heading = dashboardPage.page.getByRole("heading", {
      name: "Babysitter Observer",
    });
    await expect(heading).toBeVisible({ timeout: 30_000 });
  });

  test("filter pills are keyboard accessible buttons", async ({
    dashboardPage,
  }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();

    const pills = dashboardPage.getFilterPills();
    const count = await pills.count();
    for (let i = 0; i < count; i++) {
      const tagName = await pills.nth(i).evaluate((el) => el.tagName);
      expect(tagName.toLowerCase()).toBe("button");
    }
  });

  test("pagination buttons have aria-labels", async ({
    dashboardPage,
    page,
  }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();

    // Find a project with enough runs for pagination
    const projectsWithManyRuns = Object.entries(manifest.projectCounts)
      .filter(([_, count]) => count > 5)
      .map(([name]) => name);

    if (projectsWithManyRuns.length === 0) {
      test.skip();
      return;
    }

    const projectName = projectsWithManyRuns[0];
    const card = dashboardPage.getProjectCard(projectName);
    await card.click();

    // Expand collapsed sub-sections (Failed Runs, Completed History) if present
    await dashboardPage.expandRunSubSections();

    // Wait for runs
    const runCards = card.locator('a[href^="/runs/"]');
    await expect(runCards.first()).toBeVisible({ timeout: 15_000 });

    // Check that pagination buttons have proper aria-labels
    const prevButton = page.getByRole("button", { name: "Previous page" });
    const nextButton = page.getByRole("button", { name: "Next page" });
    await expect(prevButton).toBeVisible();
    await expect(nextButton).toBeVisible();
  });
});

// ---------------------------------------------------------------------------
// Data Integrity
// ---------------------------------------------------------------------------

test.describe("Data Integrity", () => {
  test("project card run counts match manifest data", async ({
    dashboardPage,
  }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();

    // Verify each project card exists and shows the expected total run count
    for (const [projectName, runCount] of Object.entries(
      manifest.projectCounts
    )) {
      const card = dashboardPage.getProjectCard(projectName);
      await expect(card).toBeVisible();
      // The card should contain the total run count
      await expect(card).toContainText(String(runCount));
    }
  });

  test("KPI totals are consistent with project card data", async ({
    dashboardPage,
  }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();

    // Total Runs KPI should equal the sum of all project run counts
    const totalTile = dashboardPage.getMetricTile("total-runs");
    await expect(totalTile).toContainText(String(manifest.runCount));

    // The project count should match the number of unique projects
    const projectCount = Object.keys(manifest.projectCounts).length;
    await expect(dashboardPage.projectCount).toContainText(
      `${projectCount} project`
    );
  });
});
