// Programmatic extension templates for non-shell-hook targets (Pi, oh-my-pi, etc.)

import type { TargetProfile } from './types.js';

function commandNameFromPath(cmdPath: string): string {
  const normalized = cmdPath.replace(/\\/g, '/');
  return normalized.replace(/^.*\//, '').replace(/\.md$/, '');
}

export function generateProgrammaticExtension(
  manifest: { name: string; skills?: Array<{ name: string }>; commands?: string[] | string; hooks?: Record<string, string | boolean | null> },
  targetProfile: TargetProfile,
  commandPaths?: string[]
): string {
  const piPackage = targetProfile.packageMetadata?.peerDependencyPackage ?? null;

  const pluginRootEnvVar = targetProfile.pluginRootEnvVarForExtension || 'PLUGIN_ROOT';

  const commandNameSet = new Set<string>();

  const primaryName = manifest.name;
  const excludeNames = new Set([primaryName]);

  if (manifest.skills && Array.isArray(manifest.skills)) {
    for (const skill of manifest.skills) {
      if (!excludeNames.has(skill.name)) {
        commandNameSet.add(skill.name);
      }
    }
  }

  if (commandPaths) {
    for (const cmdPath of commandPaths) {
      const name = commandNameFromPath(cmdPath);
      if (!excludeNames.has(name)) {
        commandNameSet.add(name);
      }
    }
  }

  const commandNames = Array.from(commandNameSet).sort();

  let sessionStartCall = '';
  if (manifest.hooks) {
    const ssHandler = manifest.hooks.SessionStart;
    if (typeof ssHandler === 'string' && ssHandler !== 'proxy') {
      const jsBridge = ssHandler.replace(/^hooks\//, '').replace(/\.sh$/, '.js');
      sessionStartCall = `\n  runProxiedHook("${jsBridge}", {\n    event: "session_start",\n    cwd: process.cwd(),\n  });`;
    }
  }

  if (!piPackage) {
    return `// Programmatic extension for ${targetProfile.displayName}
// Generated by extension-mux compiler

import { execSync } from "child_process";
import * as path from "path";

const PLUGIN_ROOT = path.resolve(__dirname, "..");

${generateRunProxiedHookFunction(pluginRootEnvVar)}

const COMMANDS = [
  ${commandNames.map((n) => `"${n}"`).join(', ')}
] as const;

export function activate(api: unknown): void {${sessionStartCall}
  // Register commands via target-specific API
}
`;
  }

  return `import type { ExtensionAPI } from "${piPackage}";
import { execSync } from "child_process";
import * as path from "path";

const PLUGIN_ROOT = path.resolve(__dirname, "..");

const COMMANDS = [
  ${commandNames.map((n) => `"${n}"`).join(', ')}
] as const;

function toSkillPrompt(name: string, args: string): string {
  return \`/skill:\${name}\${args ? \` \${args}\` : ""}\`;
}

${generateRunProxiedHookFunction(pluginRootEnvVar)}

export default function activate(pi: ExtensionAPI): void {${sessionStartCall}

  const forwardPrimary = async (args: unknown) => {
    pi.sendUserMessage(toSkillPrompt("${primaryName}", String(args ?? "").trim()));
  };

  pi.registerCommand("${primaryName}", {
    description: "Load the ${primaryName} skill",
    handler: forwardPrimary,
  });

  for (const name of COMMANDS) {
    const forward = async (args: unknown) => {
      pi.sendUserMessage(toSkillPrompt(name, String(args ?? "").trim()));
    };

    pi.registerCommand(name, {
      description: \`Open the \${name} skill\`,
      handler: forward,
    });

    pi.registerCommand(\`${primaryName}:\${name}\`, {
      description: \`Alias for /\${name}\`,
      handler: forward,
    });
  }
}
`;
}

function generateRunProxiedHookFunction(pluginRootEnvVar: string): string {
  return `function runProxiedHook(
  scriptName: string,
  inputData?: Record<string, unknown>
): Record<string, unknown> {
  const scriptPath = path.join(PLUGIN_ROOT, "hooks", scriptName);
  try {
    const result = execSync(\`node "\${scriptPath}"\`, {
      input: inputData ? JSON.stringify(inputData) : undefined,
      stdio: ["pipe", "pipe", "pipe"],
      timeout: 30000,
      env: {
        ...process.env,
        ${pluginRootEnvVar}: PLUGIN_ROOT,
      },
    });
    return JSON.parse(result.toString("utf8").trim());
  } catch {
    return {};
  }
}`;
}
