// Manifest generators and file copy functions for the transform stage

import * as fs from 'fs';
import * as path from 'path';
import type { A5cPluginManifest, TargetProfile, TransformedFile, Diagnostic } from './types.js';
import { getAdapter } from './targets/adapters/index.js';
import { generateProgrammaticExtension } from './proxiedHookTemplates.js';
import { generateCliBinScript, generateInstallScript, generateUninstallScript } from './binTemplates.js';
import { generateInstallInstructions } from './installInstructions.js';
import {
  generateTeamInstall,
  resolveExtraFiles,
} from './transformHelpers.js';
import { generateInstallShared } from './installSharedGenerator.js';
import {
  resolveSdkConfig,
  resolveTargetCliName,
  resolveTargetNpmPackageName,
} from './sdkConfig.js';
import { getCommandPaths } from './utils.js';

function toOutputPath(value: string): string {
  return value.replace(/\\/g, '/');
}

function getRequiredSurfaceFilename(targetProfile: TargetProfile): string | null {
  return targetProfile.requiredSurfaceFile ?? null;
}

function buildSurfaceFallback(
  manifest: A5cPluginManifest,
  targetProfile: TargetProfile,
  filename: string
): string {
  return `# ${filename}

This file was generated by @a5c-ai/extension-mux for target \`${targetProfile.name}\`.

The plugin manifest for \`${manifest.name}\` does not declare a dedicated ${filename} source file.
Add \`agents\` and/or \`contextFiles.${targetProfile.name}\` in \`plugin.json\` to replace this placeholder with real target guidance.
`;
}

function readExistingTextFile(sourceDir: string, relativePath: string): string | null {
  const fullPath = path.join(sourceDir, relativePath);
  if (!fs.existsSync(fullPath) || !fs.statSync(fullPath).isFile()) {
    return null;
  }
  return fs.readFileSync(fullPath, 'utf-8');
}

function resolveAgentSurfaceContent(
  sourceDir: string,
  manifest: A5cPluginManifest
): string | null {
  if (!manifest.agents) {
    return null;
  }

  const agentPaths = typeof manifest.agents === 'string' ? [manifest.agents] : manifest.agents;
  const contents = agentPaths
    .map((agentPath) => readExistingTextFile(sourceDir, agentPath))
    .filter((content): content is string => content !== null);

  if (contents.length === 0) {
    return null;
  }

  return contents.join('\n\n');
}

function generateCjsWrapper(moduleBasename: string, exportOnly = false): string {
  if (exportOnly) {
    return `'use strict';\n\nmodule.exports = require('./${moduleBasename}.js');\n`;
  }
  return `#!/usr/bin/env node
'use strict';

require('./${moduleBasename}.js');
`;
}

export function generateManifests(
  sourceDir: string,
  manifest: A5cPluginManifest,
  targetProfile: TargetProfile,
  _diagnostics: Diagnostic[]
): TransformedFile[] {
  const files: TransformedFile[] = [];

  // Filter manifest hooks to only those supported by this target
  // and resolve handler paths through hookFilePattern
  const sdkCfg = resolveSdkConfig(manifest);
  const filteredManifest = { ...manifest };
  if (manifest.hooks) {
    const hookFilePattern = manifest.targets?.[targetProfile.name]?.hookFilePattern
      ?? manifest.hookFilePattern;
    const pat = typeof hookFilePattern === 'string' ? hookFilePattern : undefined;
    const toSlug = (s: string) => s
      .replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()
      .replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
    const toNativeSlug = (s: string) => s.replace(/[._]/g, '-').replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

    const filtered: Record<string, string | boolean | null> = {};
    for (const [canonical, handler] of Object.entries(manifest.hooks)) {
      if (handler === null || !targetProfile.supportedHooks.has(canonical)) continue;
      if (typeof handler === 'string' && handler !== 'proxy' && pat) {
        const native = targetProfile.supportedHooks.get(canonical) || canonical;
        const resolved = 'hooks/' + pat
          .replace(/\{\{name\}\}/g, manifest.name)
          .replace(/\{\{slug\}\}/g, toSlug(canonical))
          .replace(/\{\{native\}\}/g, toNativeSlug(native));
        filtered[canonical] = resolved;
      } else {
        filtered[canonical] = handler;
      }
    }
    filteredManifest.hooks = filtered;
  }
  // Add target name to end of keywords if not already present
  if (filteredManifest.keywords) {
    const kw = [...filteredManifest.keywords];
    if (!kw.includes(targetProfile.name)) {
      kw.push(targetProfile.name);
    }
    filteredManifest.keywords = kw;
  }

  const adapter = getAdapter(targetProfile.name);
  if (adapter) {
    const adapterFiles = adapter.generateManifestFiles(sourceDir, filteredManifest, targetProfile, _diagnostics, manifest);
    files.push(...adapterFiles);
  }

  // Generate package.json for npm-distributed targets that don't already have one
  if (
    (targetProfile.distribution === 'npm-cli' || (targetProfile.distribution === 'both' && targetProfile.npmPublishable)) &&
    !files.some(f => f.path === 'package.json')
  ) {
    const packageMetadata = targetProfile.packageMetadata ?? {};
    const npmPkg = resolveTargetNpmPackageName(manifest, targetProfile);
    const cliName = resolveTargetCliName(manifest, targetProfile);
    const isEsm = packageMetadata.moduleType === 'module';
    const ext = packageMetadata.binScriptExt ?? (isEsm ? '.cjs' : '.js');
    const scripts: Record<string, string> = {
      deploy: 'npm publish --access public',
      'deploy:staging': 'npm publish --access public --tag staging',
    };
    if (packageMetadata.installLifecycle === 'plugin-scripts') {
      scripts['plugin:install'] = `node bin/install${ext} --global`;
      scripts['plugin:uninstall'] = `node bin/uninstall${ext} --global`;
    } else if (packageMetadata.installLifecycle === 'postinstall') {
      scripts.postinstall = `node bin/install${ext}`;
      scripts.preuninstall = `node bin/uninstall${ext}`;
    }
    scripts['team:install'] = `node scripts/team-install${ext}`;
    for (const [scriptName, scriptValue] of Object.entries(packageMetadata.extraScripts ?? {})) {
      scripts[scriptName] = scriptValue;
    }
    const packageFiles = ['bin/', ...(packageMetadata.extraPackageFiles ?? [])];
    packageFiles.push('hooks/', 'skills/', 'commands/', 'scripts/', 'plugin.json');
    packageFiles.push('README.md', 'versions.json', 'package.json');
    const pkgJson: Record<string, unknown> = {
      name: npmPkg,
      version: manifest.version,
      description: manifest.description,
      scripts,
      bin: { [cliName]: `bin/cli${ext}` },
      files: packageFiles,
      keywords: [manifest.name, targetProfile.name, 'orchestration'],
      author: manifest.author,
      license: manifest.license,
      publishConfig: { access: 'public' },
      dependencies: { [sdkCfg.package]: manifest.version },
    };
    if (isEsm) pkgJson.type = 'module';
    if (manifest.repository) {
      let repoUrl = typeof manifest.repository === 'string' ? manifest.repository : manifest.repository.url;
      if (!repoUrl.startsWith('git+')) repoUrl = `git+${repoUrl}`;
      if (!repoUrl.endsWith('.git')) repoUrl = `${repoUrl}.git`;
      const directory = `plugins/${npmPkg.split('/').pop()}`;
      const baseUrl = repoUrl.replace(/\.git$/, '').replace(/^git\+/, '');
      pkgJson.repository = { type: 'git', url: repoUrl, directory };
      pkgJson.homepage = `${baseUrl}/tree/main/${directory}#readme`;
      pkgJson.bugs = { url: `${baseUrl}/issues` };
    }
    if (targetProfile.adapterFamily === 'programmatic') {
      const peerPkg = packageMetadata.peerDependencyPackage;
      if (peerPkg) pkgJson.peerDependencies = { [peerPkg]: '*' };
    }
    files.push({ path: 'package.json', content: JSON.stringify(pkgJson, null, 2) + '\n' });
  }

  return files;
}

export function copyAgentFiles(
  sourceDir: string,
  manifest: A5cPluginManifest,
  targetProfile: TargetProfile,
  _diagnostics: Diagnostic[]
): TransformedFile[] {
  if (targetProfile.componentSupport?.agents !== 'native') {
    return [];
  }

  if (getRequiredSurfaceFilename(targetProfile) === 'AGENTS.md') {
    return [];
  }

  const content = resolveAgentSurfaceContent(sourceDir, manifest);
  if (!content) {
    return [];
  }

  return [{
    path: 'AGENTS.md',
    content,
  }];
}

export function copyContextFiles(
  sourceDir: string,
  manifest: A5cPluginManifest,
  targetProfile: TargetProfile,
  _diagnostics: Diagnostic[]
): TransformedFile[] {
  const requiredFilename = getRequiredSurfaceFilename(targetProfile);
  if (!requiredFilename) {
    return [];
  }

  const contextPath = manifest.contextFiles?.[targetProfile.name]
    ?? (targetProfile.name === 'gemini-cli' ? manifest.contextFiles?.gemini : undefined);
  const declaredContextContent = contextPath ? readExistingTextFile(sourceDir, contextPath) : null;
  const agentContent = resolveAgentSurfaceContent(sourceDir, manifest);
  const content = declaredContextContent
    ?? agentContent
    ?? buildSurfaceFallback(manifest, targetProfile, requiredFilename);

  return [{
    path: toOutputPath(requiredFilename),
    content,
  }];
}

export function copyIncludedFiles(
  sourceDir: string,
  manifest: A5cPluginManifest,
  excludePatterns: string[] = []
): TransformedFile[] {
  const files: TransformedFile[] = [];

  if (!manifest.include || manifest.include.length === 0) {
    return files;
  }

  for (const pattern of manifest.include) {
    if (excludePatterns.some(ex => pattern === ex || pattern.startsWith(ex))) continue;

    if (!pattern.includes('*')) {
      const fullPath = path.join(sourceDir, pattern);
      if (fs.existsSync(fullPath)) {
        const stat = fs.statSync(fullPath);
        if (stat.isFile()) {
          files.push({
            path: toOutputPath(pattern),
            content: fs.readFileSync(fullPath, 'utf-8'),
          });
        } else if (stat.isDirectory()) {
          collectDir(sourceDir, pattern, files);
        }
      }
      continue;
    }

    // Simple *.ext glob in a directory
    const dir = path.dirname(pattern);
    const ext = path.extname(pattern);
    const fullDir = path.join(sourceDir, dir);
    if (fs.existsSync(fullDir) && fs.statSync(fullDir).isDirectory()) {
      for (const entry of fs.readdirSync(fullDir)) {
        if (ext && !entry.endsWith(ext)) continue;
        const entryPath = toOutputPath(path.join(dir, entry));
        const fullEntry = path.join(sourceDir, entryPath);
        if (fs.statSync(fullEntry).isFile()) {
          files.push({
            path: entryPath,
            content: fs.readFileSync(fullEntry, 'utf-8'),
          });
        }
      }
    }
  }

  return files;
}

export function collectDir(
  sourceDir: string,
  relDir: string,
  files: TransformedFile[]
): void {
  const fullDir = path.join(sourceDir, relDir);
  for (const entry of fs.readdirSync(fullDir)) {
    const relPath = toOutputPath(path.join(relDir, entry));
    const fullPath = path.join(sourceDir, relPath);
    const stat = fs.statSync(fullPath);
    if (stat.isFile()) {
      files.push({
        path: relPath,
        content: fs.readFileSync(fullPath, 'utf-8'),
      });
    } else if (stat.isDirectory()) {
      collectDir(sourceDir, relPath, files);
    }
  }
}

export function generateExtraFiles(
  sourceDir: string,
  manifest: A5cPluginManifest,
  targetProfile: TargetProfile,
  _diagnostics: Diagnostic[]
): TransformedFile[] {
  const files: TransformedFile[] = [];
  const sdkCfg = resolveSdkConfig(manifest);

  // Generate programmatic extensions (Pi, oh-my-pi, and other programmatic targets)
  if (targetProfile.adapterFamily === 'programmatic') {
    const cmdPaths = getCommandPaths(sourceDir, manifest);
    const extensionsContent = generateProgrammaticExtension(manifest, targetProfile, cmdPaths);
    files.push({
      path: 'extensions/index.ts',
      content: extensionsContent,
    });
  }

  // Generate CLI bin scripts for npm-cli distribution targets
  if (targetProfile.distribution === 'npm-cli' || (targetProfile.distribution === 'both' && targetProfile.npmPublishable)) {
    const packageMetadata = targetProfile.packageMetadata ?? {};
    const isEsm = packageMetadata.moduleType === 'module';
    const ext = packageMetadata.binScriptExt ?? (isEsm ? '.cjs' : '.js');
    files.push({ path: `bin/cli${ext}`, content: generateCliBinScript(manifest, targetProfile), executable: true });
    files.push({ path: `bin/install${ext}`, content: generateInstallScript(manifest, targetProfile), executable: true });
    files.push({ path: `bin/uninstall${ext}`, content: generateUninstallScript(manifest, targetProfile), executable: true });
    files.push({ path: `bin/install-shared${ext}`, content: generateInstallShared(manifest, targetProfile, sourceDir) });
    files.push({ path: `scripts/team-install${ext}`, content: generateTeamInstall(manifest, targetProfile, ext), executable: true });

    if (packageMetadata.emitCjsWrappers && ext !== '.cjs') {
      files.push({ path: 'bin/cli.cjs', content: generateCjsWrapper('cli'), executable: true });
      files.push({ path: 'bin/install.cjs', content: generateCjsWrapper('install'), executable: true });
      files.push({ path: 'bin/uninstall.cjs', content: generateCjsWrapper('uninstall'), executable: true });
      files.push({ path: 'bin/install-shared.cjs', content: generateCjsWrapper('install-shared', true) });
    }
  }

  // Generate installation instructions for all targets
  files.push({
    path: 'README.md',
    content: generateInstallInstructions(manifest, targetProfile, sourceDir),
  });

  // .gitignore
  files.push({
    path: '.gitignore',
    content: `node_modules/\ndist/\n${sdkCfg.stateDir}/runs/\n${sdkCfg.stateDir}/logs/\n${sdkCfg.stateDir}/processes/\n${sdkCfg.stateDir}/artifacts/\n${sdkCfg.stateDir}/session.json\n${sdkCfg.stateDir}/current-run.json\n${sdkCfg.stateDir}/observer.json\n${sdkCfg.stateDir}/index/\n${sdkCfg.stateDir}/team/\n${sdkCfg.stateDir}/config/rules.local.json\n*.sqlite\n*.sqlite-shm\n*.sqlite-wal\n*.log\n.DS_Store\n`,
  });
  // Emit target-override extraFiles
  const extraFiles = resolveExtraFiles(manifest, targetProfile);
  if (Object.keys(extraFiles).length > 0) {
    for (const [outputPath, value] of Object.entries(extraFiles)) {
      if (value.startsWith('file:')) {
        const srcPath = value.slice(5);
        const fullPath = path.join(sourceDir, srcPath);
        if (fs.existsSync(fullPath)) {
          const isBinary = /\.(png|jpg|jpeg|gif|ico|woff2?|ttf|eot|svg|pdf)$/i.test(outputPath);
          if (isBinary) {
            files.push({
              path: outputPath,
              content: '',
              binaryContent: fs.readFileSync(fullPath),
            });
          } else {
            files.push({
              path: outputPath,
              content: fs.readFileSync(fullPath, 'utf-8'),
            });
          }
        }
      } else {
        files.push({ path: outputPath, content: value });
      }
    }
  }
  if (manifest.postInstall) {
    const postInstallPath = path.join(sourceDir, manifest.postInstall);
    if (fs.existsSync(postInstallPath)) {
      files.push({ path: 'scripts/post-install.js', content: fs.readFileSync(postInstallPath, 'utf-8'), executable: true });
    }
  }
  const adapter = getAdapter(targetProfile.name);
  if (adapter) {
    const adapterExtraFiles = adapter.generateExtraTargetFiles(sourceDir, manifest, targetProfile, _diagnostics);
    files.push(...adapterExtraFiles);
  }
  return files;
}
