/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const strictDocScope = process.env.DOCS_STRICT_SCOPE === '1';

const strictSidebar = [
  'cli-examples',
  'github-actions-setup-babysitter',
  'github-actions-setup-claude-code',
  'github-actions-setup-codex',
  'github-actions-setup-gemini-cli',
  {
    type: 'category',
    label: 'Reference',
    items: ['reference/GETTING_STARTED', 'reference/babysitter_cli_surface_spec']
  },
  {
    type: 'category',
    label: 'V6 Roadmap',
    items: ['v6-spec-and-roadmap/README', 'v6-spec-and-roadmap/testing-framework', 'v6-spec-and-roadmap/v6-implementation-roadmap']
  }
];

const curatedSidebar = [
  {
    type: 'category',
    label: 'Start Here',
    collapsible: false,
    items: [
      'user-guide/index',
      'package-and-plugin-map',
      { type: 'autogenerated', dirName: 'user-guide/getting-started' },
      { type: 'autogenerated', dirName: 'user-guide/tutorials' },
      { type: 'autogenerated', dirName: 'user-guide/features' },
      { type: 'autogenerated', dirName: 'user-guide/reference' }
    ]
  },
  {
    type: 'category',
    label: 'Integrate & Extend',
    items: [
      'assimilation/index',
      { type: 'autogenerated', dirName: 'assimilation/harness' },
      'github-actions-setup-babysitter',
      'github-actions-setup-claude-code',
      'github-actions-setup-codex',
      'github-actions-setup-gemini-cli',
      'plugins',
      { type: 'autogenerated', dirName: 'plugins' },
      'agent-mux/README',
      { type: 'autogenerated', dirName: 'agent-mux/tutorials' },
      { type: 'autogenerated', dirName: 'agent-mux/reference' },
      { type: 'autogenerated', dirName: 'agent-mux/archive' }
    ]
  },
  {
    type: 'category',
    label: 'Operate & Maintain',
    items: [
      'cli-examples',
      'workspace-validation',
      'release-pipeline',
      { type: 'autogenerated', dirName: 'testing' },
      { type: 'autogenerated', dirName: 'reference' },
      { type: 'autogenerated', dirName: 'agent-reference' }
    ]
  },
  {
    type: 'category',
    label: 'Architecture & Background',
    items: [
      { type: 'autogenerated', dirName: 'v6-spec-and-roadmap' },
      { type: 'autogenerated', dirName: 'articles' }
    ]
  }
];

module.exports = {
  docsSidebar: strictDocScope ? strictSidebar : curatedSidebar
};
