// Programmatic extension for OpenCode
// Generated by agent-plugins-mux compiler

import { execSync } from "child_process";
import * as path from "path";

const PLUGIN_ROOT = path.resolve(__dirname, "..");

function runProxiedHook(
  scriptName: string,
  inputData?: Record<string, unknown>
): Record<string, unknown> {
  const scriptPath = path.join(PLUGIN_ROOT, "hooks", scriptName);
  try {
    const result = execSync(`node "${scriptPath}"`, {
      input: inputData ? JSON.stringify(inputData) : undefined,
      stdio: ["pipe", "pipe", "pipe"],
      timeout: 30000,
      env: {
        ...process.env,
        PLUGIN_ROOT: PLUGIN_ROOT,
      },
    });
    return JSON.parse(result.toString("utf8").trim());
  } catch {
    return {};
  }
}

const COMMANDS = [
  "assimilate", "babysit", "call", "cleanup", "contrib", "doctor", "forever", "help", "observe", "plan", "plugins", "project-install", "resume", "retrospect", "user-install", "yolo"
] as const;

export function activate(api: unknown): void {
  runProxiedHook("session-start.js", {
    event: "session_start",
    cwd: process.cwd(),
  });
  // Register commands via target-specific API
}
