apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: refpolicies.krate.a5c.ai
spec:
  group: krate.a5c.ai
  scope: Namespaced
  names:
    plural: refpolicies
    singular: refpolicy
    kind: RefPolicy
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
            required:
            - organizationRef
            properties:
              organizationRef:
                type: string
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: runnerpools.krate.a5c.ai
spec:
  group: krate.a5c.ai
  scope: Namespaced
  names:
    plural: runnerpools
    singular: runnerpool
    kind: RunnerPool
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              organizationRef:
                type: string
              warmReplicas:
                type: integer
              maxReplicas:
                type: integer
            required:
            - organizationRef
            - warmReplicas
            - maxReplicas
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webhooksubscriptions.krate.a5c.ai
spec:
  group: krate.a5c.ai
  scope: Namespaced
  names:
    plural: webhooksubscriptions
    singular: webhooksubscription
    kind: WebhookSubscription
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              organizationRef:
                type: string
              url:
                type: string
              events:
                type: array
                items:
                  type: string
            required:
            - organizationRef
            - url
            - events
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: views.krate.a5c.ai
spec:
  group: krate.a5c.ai
  scope: Namespaced
  names:
    plural: views
    singular: view
    kind: View
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - organizationRef
            - selector
            properties:
              organizationRef:
                type: string
              selector:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              columns:
                type: array
                items:
                  type: string
              sort:
                type: array
                items:
                  type: string
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: selectors.krate.a5c.ai
spec:
  group: krate.a5c.ai
  scope: Namespaced
  names:
    plural: selectors
    singular: selector
    kind: Selector
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              organizationRef:
                type: string
              labels:
                type: object
                additionalProperties:
                  type: string
              query:
                type: string
            required:
            - organizationRef
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pullrequests.krate.a5c.ai
spec:
  group: krate.a5c.ai
  scope: Namespaced
  names:
    plural: pullrequests
    singular: pullrequest
    kind: PullRequest
    shortNames:
    - pr
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - organizationRef
            - repository
            - title
            properties:
              organizationRef:
                type: string
              repository:
                type: string
              title:
                type: string
              head:
                type: string
              base:
                type: string
              body:
                type: string
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: issues.krate.a5c.ai
spec:
  group: krate.a5c.ai
  scope: Namespaced
  names:
    plural: issues
    singular: issue
    kind: Issue
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - organizationRef
            - title
            properties:
              organizationRef:
                type: string
              repository:
                type: string
              title:
                type: string
              body:
                type: string
              labels:
                type: array
                items:
                  type: string
              assignees:
                type: array
                items:
                  type: string
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: reviews.krate.a5c.ai
spec:
  group: krate.a5c.ai
  scope: Namespaced
  names:
    plural: reviews
    singular: review
    kind: Review
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - organizationRef
            - pullRequest
            properties:
              organizationRef:
                type: string
              pullRequest:
                type: string
              decision:
                type: string
              body:
                type: string
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pipelines.krate.a5c.ai
spec:
  group: krate.a5c.ai
  scope: Namespaced
  names:
    plural: pipelines
    singular: pipeline
    kind: Pipeline
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - organizationRef
            - repository
            - ref
            x-kubernetes-preserve-unknown-fields: true
            properties:
              organizationRef:
                type: string
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jobs.krate.a5c.ai
spec:
  group: krate.a5c.ai
  scope: Namespaced
  names:
    plural: jobs
    singular: job
    kind: Job
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - organizationRef
            - pipeline
            - step
            x-kubernetes-preserve-unknown-fields: true
            properties:
              organizationRef:
                type: string
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webhookdeliveries.krate.a5c.ai
spec:
  group: krate.a5c.ai
  scope: Namespaced
  names:
    plural: webhookdeliveries
    singular: webhookdelivery
    kind: WebhookDelivery
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - organizationRef
            - subscription
            - eventType
            - signature
            x-kubernetes-preserve-unknown-fields: true
            properties:
              organizationRef:
                type: string
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
