import type { AmuxAdapterMetadata } from "./amuxMetadata";

const FALLBACK_SESSION_DIR = ".a5c/runs";

export const STATIC_FALLBACK_METADATA: Record<string, AmuxAdapterMetadata> = {
  claude: {
    name: "claude",
    hostEnvSignals: ["CLAUDE_ENV_FILE"],
    capabilities: {
      supportsSkills: true,
      supportsThinking: true,
      supportsMCP: true,
      requiresToolApproval: true,
      supportsInteractiveMode: true,
      supportsStdinInjection: true,
      supportsSubagentDispatch: false,
      supportsParallelExecution: false,
      supportsImageInput: true,
      hasRuntimeHooks: true,
      hasStopHook: true,
    },
    sessionDir: FALLBACK_SESSION_DIR,
  },
  codex: {
    name: "codex",
    hostEnvSignals: ["CODEX_THREAD_ID", "CODEX_SESSION_ID", "CODEX_PLUGIN_ROOT"],
    capabilities: {
      supportsSkills: true,
      supportsThinking: true,
      supportsMCP: false,
      requiresToolApproval: false,
      supportsInteractiveMode: true,
      supportsStdinInjection: true,
      supportsSubagentDispatch: false,
      supportsParallelExecution: false,
      supportsImageInput: true,
      hasRuntimeHooks: true,
      hasStopHook: true,
    },
    sessionDir: FALLBACK_SESSION_DIR,
  },
  cursor: {
    name: "cursor",
    hostEnvSignals: ["CURSOR_PROJECT_DIR", "CURSOR_VERSION"],
    capabilities: {
      supportsSkills: true,
      supportsThinking: true,
      supportsMCP: false,
      requiresToolApproval: false,
      supportsInteractiveMode: true,
      supportsStdinInjection: true,
      supportsSubagentDispatch: false,
      supportsParallelExecution: false,
      supportsImageInput: true,
      hasRuntimeHooks: true,
      hasStopHook: true,
    },
    sessionDir: FALLBACK_SESSION_DIR,
  },
  gemini: {
    name: "gemini",
    hostEnvSignals: ["GEMINI_SESSION_ID", "GEMINI_CWD", "GEMINI_PROJECT_DIR"],
    capabilities: {
      supportsSkills: true,
      supportsThinking: true,
      supportsMCP: false,
      requiresToolApproval: false,
      supportsInteractiveMode: true,
      supportsStdinInjection: true,
      supportsSubagentDispatch: false,
      supportsParallelExecution: false,
      supportsImageInput: true,
      hasRuntimeHooks: true,
      hasStopHook: true,
    },
    sessionDir: FALLBACK_SESSION_DIR,
  },
  copilot: {
    name: "copilot",
    hostEnvSignals: ["COPILOT_SESSION_ID"],
    capabilities: {
      supportsSkills: true,
      supportsThinking: true,
      supportsMCP: false,
      requiresToolApproval: false,
      supportsInteractiveMode: true,
      supportsStdinInjection: true,
      supportsSubagentDispatch: false,
      supportsParallelExecution: false,
      supportsImageInput: true,
      hasRuntimeHooks: true,
      hasStopHook: true,
    },
    sessionDir: FALLBACK_SESSION_DIR,
  },
  omp: {
    name: "omp",
    hostEnvSignals: ["OMP_SESSION_ID"],
    capabilities: {
      supportsSkills: true,
      supportsThinking: true,
      supportsMCP: false,
      requiresToolApproval: false,
      supportsInteractiveMode: true,
      supportsStdinInjection: true,
      supportsSubagentDispatch: false,
      supportsParallelExecution: false,
      supportsImageInput: true,
      hasRuntimeHooks: true,
      hasStopHook: true,
    },
    sessionDir: FALLBACK_SESSION_DIR,
  },
  opencode: {
    name: "opencode",
    hostEnvSignals: ["AGENT_SESSION_ID", "OPENCODE_SESSION_ID"],
    capabilities: {
      supportsSkills: true,
      supportsThinking: true,
      supportsMCP: false,
      requiresToolApproval: false,
      supportsInteractiveMode: true,
      supportsStdinInjection: true,
      supportsSubagentDispatch: false,
      supportsParallelExecution: false,
      supportsImageInput: true,
      hasRuntimeHooks: true,
      hasStopHook: true,
    },
    sessionDir: FALLBACK_SESSION_DIR,
  },
  openclaw: {
    name: "openclaw",
    hostEnvSignals: [],
    capabilities: {
      supportsSkills: true,
      supportsThinking: true,
      supportsMCP: false,
      requiresToolApproval: false,
      supportsInteractiveMode: true,
      supportsStdinInjection: true,
      supportsSubagentDispatch: false,
      supportsParallelExecution: false,
      supportsImageInput: true,
      hasRuntimeHooks: false,
      hasStopHook: false,
    },
    sessionDir: FALLBACK_SESSION_DIR,
  },
  pi: {
    name: "pi",
    hostEnvSignals: ["PI_SESSION_ID"],
    capabilities: {
      supportsSkills: true,
      supportsThinking: true,
      supportsMCP: false,
      requiresToolApproval: false,
      supportsInteractiveMode: true,
      supportsStdinInjection: true,
      supportsSubagentDispatch: false,
      supportsParallelExecution: false,
      supportsImageInput: true,
      hasRuntimeHooks: false,
      hasStopHook: false,
    },
    sessionDir: FALLBACK_SESSION_DIR,
  },
};
