/**
 * Re-export shim — canonical implementation lives in @a5c-ai/agent-runtime.
 * Internal babysitter-agent consumers continue to import via relative paths
 * through this barrel file.
 */
export {
  startDaemon,
  stopDaemon,
  getDaemonStatus,
  loadDaemonConfig,
  writeDaemonConfig,
  createFileWatcher,
  createWebhookListener,
  createTimerScheduler,
  runDaemonLoop,
  readDaemonLoopStatus,
  appendDaemonLog,
  readDaemonLog,
  type DaemonConfig,
  type DaemonStartOptions,
  type DaemonStartOutput,
  type DaemonStopOptions,
  type DaemonStopOutput,
  type DaemonStatusOptions,
  type DaemonStatusOutput,
  type DaemonMetadata,
  type TriggerConfig,
  type TriggerEvent,
  type FileTriggerEvent,
  type AutomationTriggerEvent,
  type FileTriggerConfig,
  type FileWatcherHandle,
  type WebhookListenerOptions,
  type WebhookListenerHandle,
  type TriggerCallback,
  type TimerSchedulerHandle,
  type DaemonLoopOptions,
  type DaemonLoopStatus,
  type DaemonLogEntry,
} from "@a5c-ai/agent-runtime/daemon";
